version: '3'
#
#volumes:
#  contents:

services:
  docsify:
    image: app:latest
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/docs:/opt/docs:rw
      - ${PWD}/scripts:/opt/scripts:ro
#      - contents:/opt/docs/contents
    working_dir: /opt/scripts
    entrypoint: ./entrypoint.sh
    command: serve /opt/docs -l 3000
    tty: true
