version: '3'

volumes:
  contents:

services:
  docsify:
    image: app:latest
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/docs:/opt/docs:rw
      - contents:/opt/docs/contents
    command: npx serve /opt/docs -l 3000
    tty: true
